### ISSUE TITLE
Test parsing of register remarks

### ISSUE THREAD

**Issue by fkraeutli** [swiss-art-research-net/itten-pipeline#82]
Try parser on register remarks that might also contain structured information

**Comment by fkraeutli** [comment]
Parsing works, however remarks format does not follow same pattern as internal remarks. e.g.
```Link zur GND: <a href=http://d-nb.info/gnd/120241986 target=\"_blank\">GND</a> / Andere Namen: Mazzucchelli Argan, Anna Maria / Beziehungen zu Personen: Argan, Giulio Carlo #GND119270323 (Ehemann)```

Should be "Beziehungen:" instead of "Beziehungen zu Personen:"

(also still need to extend parser to include Beziehungen https://github.com/swiss-art-research-net/itten-pipeline/issues/73)

cc @kikilutz

**Comment by fkraeutli** [comment]
> Yes, will need to adapt syntax in Bemerkungen of register. Will need some time....

me too ;)

**Comment by kikilutz** [comment]
@fkraeutli Just discussed this with Christine and we decided to go about issue in a different way:  All registers will be linked either to GND or Wikidata identities in the future (those which do not qualify for either, will be treated the same as non identified entities and transfered in the field "Allgemeine interne Bemerkungen"). Relations will then be defined on GND or Wikidata-level: Hence no need to invest time in order to parse relations out of the field "Bemerkungen" in registers.

**Comment by fkraeutli** [comment]
Sounds good, thanks for clarifying!
